/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Gradle plugin project to get you started.
 * For more details on writing Custom Plugins, please refer to https://docs.gradle.org/9.5.0/userguide/custom_plugins.html in the Gradle documentation.
 */

plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
}

group = "com.buildoptimus"

gradlePlugin {
    website = "https://github.com/BuildOptimus/kmp-launcher-icons"
    vcsUrl = "https://github.com/BuildOptimus/kmp-launcher-icons.git"

    plugins {
        create("kmp-launcher-icons") {
            id = "com.buildoptimus.kmp-launcher-icons"
            displayName = "KMP Launcher Icons"
            description = "Generate native launcher icon resources from a unified Kotlin DSL"
            tags = setOf(
                "kotlin",
                "multiplatform",
                "kmp",
                "compose",
                "cmp",
                "launcher",
                "icons",
                "android",
                "ios",
                "desktop"
            )
            implementationClass = "com.buildoptimus.kmp_launcher_icons.KmpLauncherIconsPlugin"
        }
    }
}
